export const presets = {
  orders: {
    name: "Order routing",
    description:
      "Calculate an order total, route high-value orders, and test a retry.",
    input: {
      customer: { name: "Maya", email: "maya@example.com" },
      subtotal: 240,
      currency: "USD",
    },
    nodes: [
      {
        id: "receive",
        name: "Order received",
        type: "trigger",
        config: {},
        next: "total",
        x: 45,
        y: 170,
      },
      {
        id: "total",
        name: "Calculate total",
        type: "transform",
        config: {
          action: "multiply",
          field: "total",
          source: "subtotal",
          factor: 1.15,
        },
        next: "route",
        x: 270,
        y: 170,
      },
      {
        id: "route",
        name: "High value?",
        type: "condition",
        config: { field: "total", operator: "gte", value: 200 },
        next: "notify",
        otherwise: "standard",
        x: 495,
        y: 170,
      },
      {
        id: "notify",
        name: "Notify account team",
        type: "http",
        config: { fixture: "crm", failures: 1, retries: 2 },
        next: "complete",
        x: 720,
        y: 70,
      },
      {
        id: "standard",
        name: "Standard fulfilment",
        type: "delay",
        config: { ms: 120 },
        next: "complete",
        x: 720,
        y: 280,
      },
      {
        id: "complete",
        name: "Order processed",
        type: "output",
        config: {
          message:
            "Order for {{customer.name}} processed. Total: {{total}} {{currency}}.",
        },
        x: 950,
        y: 170,
      },
    ],
  },
  leads: {
    name: "Lead qualification",
    description:
      "Route qualified leads to a simulated CRM and keep a trace of both branches.",
    input: {
      name: "Avery Chen",
      company: "North Studio",
      score: 82,
      source: "website",
    },
    nodes: [
      {
        id: "receive",
        name: "New lead",
        type: "trigger",
        config: {},
        next: "label",
        x: 45,
        y: 170,
      },
      {
        id: "label",
        name: "Build contact label",
        type: "transform",
        config: {
          action: "set",
          field: "label",
          value: "{{name}} at {{company}}",
        },
        next: "qualify",
        x: 270,
        y: 170,
      },
      {
        id: "qualify",
        name: "Score above 70?",
        type: "condition",
        config: { field: "score", operator: "gte", value: 70 },
        next: "crm",
        otherwise: "nurture",
        x: 495,
        y: 170,
      },
      {
        id: "crm",
        name: "Create CRM contact",
        type: "http",
        config: { fixture: "crm", failures: 0, retries: 2 },
        next: "done",
        x: 720,
        y: 70,
      },
      {
        id: "nurture",
        name: "Add nurture tag",
        type: "transform",
        config: { action: "set", field: "segment", value: "nurture" },
        next: "done",
        x: 720,
        y: 280,
      },
      {
        id: "done",
        name: "Lead saved",
        type: "output",
        config: { message: "{{label}} is ready for follow-up." },
        x: 950,
        y: 170,
      },
    ],
  },
  recovery: {
    name: "Retry laboratory",
    description:
      "A deterministic failure fixture. Increase retries to recover the run.",
    input: { invoice: "INV-1042", amount: 420 },
    nodes: [
      {
        id: "receive",
        name: "Invoice ready",
        type: "trigger",
        config: {},
        next: "billing",
        x: 180,
        y: 170,
      },
      {
        id: "billing",
        name: "Billing fixture",
        type: "http",
        config: { fixture: "billing", failures: 2, retries: 1 },
        next: "done",
        x: 475,
        y: 170,
      },
      {
        id: "done",
        name: "Receipt issued",
        type: "output",
        config: { message: "Receipt created for {{invoice}}." },
        x: 770,
        y: 170,
      },
    ],
  },
};
export const copyPreset = (key) =>
  JSON.parse(JSON.stringify(presets[key] || presets.orders));
